Upgrade cron library to maintained go-co-op/gocron
privacybydesign/irmago pull request #219
Opened 2022-04-22 05:52 UTC by reinkrul

The current scheduler library (https://github.com/jasonlvhit/gocron) has been abandoned and causes race conditions (https://github.com/privacybydesign/irmago/issues/57). There is an active fork from the maintainers that inherited the original project, which is an (almost) drop-in replacement: https://github.com/go-co-op/gocron

This PR replaces jasonlvhit/gocron with go-co-op/gocron

2022-04-26 10:45 UTC, sietseringers commented
Thanks!

There are a few small issues with the PR, due to differences between the previous `gocron` and this one:

* The `Every()` method no longer accepts `uint64` parameters, which `irmago` uses at several invocations;
* The `Do()` method now returns an error, which complains about the above, but since the `Do()` method of the previous `gocron` did not return an error, this error is now ignored. This is why several of the unit tests failed. Ideally, at all invocations of the `Do()` method the error should be checked.

Additionally, when I build it a few changes are made to `go.mod` and `go.sum`.

Would you like to fix these issues? If not, we'd be happy to do that ourselves.

2022-04-26 11:05 UTC, reinkrul commented
> Would you like to fix these issues? If not, we'd be happy to do that ourselves.

I was just investigating these myself and am halfway fixing the same issues you found. I can probably push those fixes somewhere this week.

2022-04-28 04:29 UTC, reinkrul commented
I had to write some hacky code to wait for the scheduler jobs to finish when running unit tests. Otherwise the tests would fail on my development system (too slow on a Macbook?), when I increased the `Sleep()`'s here and there it mostly worked. The code I introduced to run all scheduler jobs and wait for them to finish might be a bit of a better solution than the sleeps, but still not very good.

I made a feature request in the scheduler repository to have it properly support unit testing; https://github.com/go-co-op/gocron/issues/326

2022-06-09 14:44 UTC, sietseringers requested changes
Hi, sorry this has been quiet for so long. I figured out what caused the tests to fail, see the comments. After this, the PR should be fine to merge. Thanks!

2022-06-09 14:44 UTC, sietseringers commented on internal/sessiontest/revocation_test.go
> -		time.Sleep(time.Second)
This line causes a timestamp to be updated, which is verified below using `require.NotEqual(t, sacctime, sacc.Accumulator.Time)`. The removal of this line causes this to fail, can you reinstate it?

2022-06-09 14:44 UTC, sietseringers commented on internal/sessiontest/revocation_test.go
> -		time.Sleep(100 * time.Millisecond)
This line should be reinstated as well; its purpose was not to wait for the scheduler to finish its jobs, but instead to give time to finish running to a HTTP handler which is invoked by a job.

2022-06-10 04:26 UTC, reinkrul commented
I must admit the PR wasn't on my mind anymore, thanks for finding out what I broke ;-) . I reverted the changes and adjusted the comments a bit.

2022-06-10 08:11 UTC, sietseringers commented
Great, thanks!

2022-06-10 08:12 UTC, sietseringers approved these changes

2022-06-10 08:12 UTC, merged