chore: version bump
privacybydesign/irmago pull request #288
Opened 2023-02-23 15:38 UTC by sanderhollaar

2023-02-23 15:43 UTC, bobhageman approved these changes

2023-02-24 13:50 UTC, ivard requested changes

2023-02-24 13:50 UTC, ivard commented on CHANGELOG.md
> +## [0.11.3] - 2023-02-23
This should be 0.12.0, because it introduces new functionality.

2023-02-24 13:50 UTC, ivard commented on CHANGELOG.md
> + - Add 403 invalid token error response
As a third party this won't be clear to me what has been changed. In my view, it is also a 'Changed' instead of an 'Added'.

2023-02-24 13:50 UTC, ivard commented on CHANGELOG.md
> + - Dependency version bumps
This is not a 'Fixed', but 'Security' and then we should better explain what we fixed.

2023-02-24 13:50 UTC, ivard commented on CHANGELOG.md
> +[0.11.3]: https://github.com/privacybydesign/irmago/compare/v0.11.2...v0.11.3
Here too, the version should be different.

2023-02-24 13:50 UTC, ivard commented on version.go
> +const Version = "0.11.3"
Different version.

2023-02-28 11:21 UTC, ivard submitted a review, later dismissed

2023-02-28 12:07 UTC, sjoerdlmkns approved these changes

2023-02-28 12:30 UTC, ivard approved these changes

2023-02-28 12:42 UTC, merged